kind: Deployment
apiVersion: apps/v1
metadata:
  name: icecream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecream
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: icecream
    spec:
      containers:
        - name: icecream
          image: 'registry.ocp4.pacosta.com:8443/microfrontend/icecream:2'
          ports:
            - containerPort: 3002
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-12-12T11:18:22Z'
      lastTransitionTime: '2023-12-12T11:18:22Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-12-12T11:18:22Z'
      lastTransitionTime: '2023-12-12T11:18:12Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "icecream-bf6878d87" has successfully progressed.
